## Import Nessessary Libraries

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.metrics import accuracy_score

In [4]:
from sklearn.metrics import confusion_matrix

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
from sklearn.preprocessing import LabelEncoder

In [11]:
import seaborn as sns

In [14]:
from sklearn.datasets import load_breast_cancer

In [20]:
from sklearn.model_selection import train_test_split

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
from sklearn.svm import SVC 

In [27]:
from sklearn.metrics import  classification_report

In [45]:
from sklearn.neighbors import KNeighborsClassifier

## Load Breast Cancer Dataset 

In [15]:
data = load_breast_cancer() 

In [28]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [29]:
X = data.data

In [30]:
y = data.target

## Preprocess Data

In [31]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Split Data Into Training And Testing Sets 

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42)

## Classification Alorithm Implementation

## 1. Logistic Regression 

In [36]:
logreg = LogisticRegression(max_iter=1000).fit(X_train,y_train)
y_pred_logreg = logreg.predict(X_test)

## 2. Decision Tree Classifier

In [38]:
dt = DecisionTreeClassifier().fit(X_train,y_train)
y_pred_dt = dt.predict(X_test)

## 3. Random Forest Classifier

In [39]:
rf = RandomForestClassifier().fit(X_train,y_train)
y_pred_rf = rf.predict(X_test)

## 4. Support Vector Machine(SVM)

In [40]:
svm = SVC().fit(X_train,y_train)
y_pred_svm = svm.predict(X_test)

## 5. K-Nearest Neighbors(k-NN)

In [46]:
knn = KNeighborsClassifier(n_neighbors=5).fit(X_train,y_train)
y_pred_knn = knn.predict(X_test)

## Model Comparison

## Accuracy Scores

In [49]:
print("Accuracy Scores : ")
print("Logistic Regression : ",accuracy_score(y_test,y_pred_logreg))
print("Decision Tree : ",accuracy_score(y_test,y_pred_dt))
print("Random Forest : ",accuracy_score(y_test,y_pred_rf))
print("SVM : ",accuracy_score(y_test,y_pred_svm))
print("k-NN : ",accuracy_score(y_test,y_pred_knn))

Accuracy Scores : 
Logistic Regression :  0.9736842105263158
Decision Tree :  0.9473684210526315
Random Forest :  0.956140350877193
SVM :  0.9736842105263158
k-NN :  0.9473684210526315


## Classification Reports

In [51]:
print("Classification Reports : ")
print("Logistic Regression : ")    
print(classification_report(y_test,y_pred_logreg))
print("Decision Tree :")
print(classification_report(y_test,y_pred_dt))
print("Random Forest : ")
print(classification_report(y_test,y_pred_rf))
print("SVM : ")
print(classification_report(y_test,y_pred_svm))
print("k-NN : ")
print(classification_report(y_test,y_pred_knn))
      
      

Classification Reports : 
Logistic Regression : 
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Decision Tree :
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

Random Forest : 
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        43
           1       0.96      0.97      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95   

## Confusion Matrics 

In [54]:
print(" Confusion Matrics : ")
print("Logistic Regression : ")    
print(confusion_matrix(y_test,y_pred_logreg))
print("Decision Tree :")
print(confusion_matrix(y_test,y_pred_dt))
print("Random Forest : ")
print(confusion_matrix(y_test,y_pred_rf))
print("SVM : ")
print(confusion_matrix(y_test,y_pred_svm))
print("k-NN : ")
print(confusion_matrix(y_test,y_pred_knn))
      

 Confusion Matrics : 
Logistic Regression : 
[[41  2]
 [ 1 70]]
Decision Tree :
[[40  3]
 [ 3 68]]
Random Forest : 
[[40  3]
 [ 2 69]]
SVM : 
[[41  2]
 [ 1 70]]
k-NN : 
[[40  3]
 [ 3 68]]
